services:
  db:
    image: postgres:16-alpine
    container_name: toluja-db
    environment:
      POSTGRES_DB: toluja
      POSTGRES_USER: toluja
      POSTGRES_PASSWORD: toluja
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toluja -d toluja"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: toluja-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/toluja
      SPRING_DATASOURCE_USERNAME: toluja
      SPRING_DATASOURCE_PASSWORD: toluja
      PRINTERS_MODE: agent
      PRINTERS_PRINTER1: IMPRESSORA1
      PRINTERS_PRINTER2: IMPRESSORA2
      PRINTERS_PRINTER3: IMPRESSORA3
      PRINTERS_AGENT_STORE_ID: store-001
      PRINTERS_AGENT_DEVICE_ID: agent-store-001
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: toluja-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - default
      - proxy

  db-wp:
    image: mariadb:11.4
    container_name: toluja-db-wp
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 4102
      MYSQL_ROOT_PASSWORD: 4102
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p4102 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - default

  wordpress:
    image: wordpress:latest
    container_name: toluja-wordpress
    depends_on:
      db-wp:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db-wp:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 4102
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/toluja-go-landing:/var/www/html/wp-content/themes/toluja-go-landing
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - default
      - proxy
  #     - default
  #     - proxy

volumes:
  db_data:
  wp_db_data:

networks:
  proxy:
    external: true
